### ISSUE TITLE
23.05 ZHF Developer Workshop Feedback

### ISSUE THREAD

**Issue by ners** [nix-community/ZurichZHF#1]
Dear Nixers!

Thank you for participating in the developer workshop that we ran on 2023-05-27. We sincerely appreciate your presence and active involvement in making it a successful event. We would like to hear your feedback and insights to help us improve future events. Your input is invaluable to us!

We kindly request you to take a few minutes to provide your feedback. Here are some example questions to consider; **you don't have to answer all of them**.

1. Organization:
  - How would you rate the overall organization of the workshop?
  - Did you find the registration process smooth and hassle-free?
  - Were the communication channels (meetup chat, Matrix room) effective?

2. Content:
  - Did the workshop content align with your expectations and needs?
  - Which specific topics or areas covered during the workshop were most valuable to you?
  - Were there any topics or areas that you felt were lacking or could be improved upon?

3. Atmosphere and networking:
  - Did you find the workshop environment conducive to learning and networking?
  - Were there enough opportunities to interact with other attendees and exchange ideas?
  - Did you feel comfortable asking questions and participating in discussions?

4. Logistics:
  - Were the venue and facilities suitable for the workshop?
  - Did you encounter any issues with seating, audiovisual equipment, or other logistics?
  - How would you rate the overall timing and duration of the workshop?

5. Suggestions for improvement:
  - Do you have any suggestions or ideas for improving future workshops?
  - Are there any specific topics or formats you would like to see in future events?
  - Is there anything else you would like to share that would help us enhance the workshop experience?

@aherrmann
@basvandijk
@chysi
@christianharke
@DavHau
@edolstra
@fabian-gubler
@flokli
@gefla
@ivanbakel
@imincik
@Ericson2314
@rekk
@lorenz
@MrcJkb
@prtzl
@nh2
@das-g
@roberth
@infinisil
@SebastienDeriaz
@fricklerhandwerk
@rwxg
@Eltonux
@Nebucatnetzer

**Comment by SebastienDeriaz** [comment]
Thanks to everybody for the event, it was a blast ! 

1. Organisation (be it the event, the communicative channels, etc...) was top notch !

2. I found the content to be fairly involved but very interesting still. I particularly enjoyed the workshop as it was a great opportunity to exchange our views and knowledge.

3. The environment was great, both for learning and networking. I found it rather difficult to ask questions and participate due to a significant lack of knowledge on multiple subjects, but that's personnal

4. Timing, location, logistics, all of it was 10/10

5. The bar was set pretty high, it's hard to beat :) if I were to change anything, I would consider having a more beginner-friendly workshop or some idea of the sort

**Comment by mrcjkb** [comment]
1. Great organisation, great food! Matrix is my preferred communication channel, so I was happy with that.

1. I found it great to hear about different ways I can contribute to improving the nix ecosystem. Learned quite a few things that were new to me, too.
1. Overall, it felt like a very comfortable environment to me.
1. The facilities were great (only minor complaint is the locked door). It would have been nice to have had a bit more time to fix some hydra failures, but I can do that in my own time, too.

**Comment by das-g** [comment]
> 1. Organization:
> 
> 
>     * How would you rate the overall organization of the workshop?

:+1:

Caveat: It'd be good to pro-actively reach out to volunteers like me, so that they don't have to inquire when they should be where (like I had to).

>    * Did you find the registration process smooth and hassle-free?

As I already had a Meetup.com account, yes. Though I'd prefer if FLOSS events would not rely on such services that require JavaScript served from various domains to work and whose business model might (at least partially) be based on collecting the users' data and selling it to marketers, or to allow others to do so. (Whether that's actually the case for Meetup.com, I don't know.) A CryptPad form would probably have been sufficient and similarly easy to set up.

>    * Were the communication channels (meetup chat, Matrix room) effective?

Matrix room: Yes. :+1: (And I'd have preferred to use _only_ that.) Though, it'd be good to set up the room and inform participants about its address already before the event.

Meetup chat: It was quite hard to copy the matrix room address that was posted there, as the text selection would often get lost before I had a chance to hit <kbd>Ctrl</kbd>+<kbd>c</kdb>.

>    2. Content:
> 
> 
>    * Did the workshop content align with your expectations and needs?

Yes. :+1:

>    * Which specific topics or areas covered during the workshop were most valuable to you?

- Informal conversation on the hallways and during the little time of ZHF hacking.
- The lightning talks about documentation and Nix maintenance.

>    * Were there any topics or areas that you felt were lacking or could be improved upon?

The UX workshop material should have been adapted ahead-of-time to fit a volunteer-driven FLOSS community rather than a for-profit enterprise. It would also have been good to set aside sufficient time for the "goal alighment" phase, rather than rushing participants through its steps and sometimes cutting necessary discussions short prematurely. (Cutting discussions short when they can't lead anywhere was of course good, but that IMO wasn't the case with all discussions that were cut short.)
 
>    3. Atmosphere and networking:
> 
> 
>    * Did you find the workshop environment conducive to learning and networking?
>
>    * Were there enough opportunities to interact with other attendees and exchange ideas?
> 
>    * Did you feel comfortable asking questions and participating in discussions?

Yes to all three! :+1:

>    4. Logistics:
> 
> 
>    * Were the venue and facilities suitable for the workshop?

Yes.

Though it'd have been good to get some guest OST badges for the organizers (which is possible for such events).
 
>    * Did you encounter any issues with seating, audiovisual equipment, or other logistics?

No major ones, but we should maybe ask speakers not to touch any buttons of the projector panel without consulting the local guy (this time: me) first. Some turned off the projector unnecessarily, which cost some time (because the projector can't be turned back on before it has cooled down or whatever) and thus (slightly) added to the schedule delays.

>    * How would you rate the overall timing and duration of the workshop?

Two days for the overall combined event was a good duration. It'd be nice to have more time for hacking even when attending all the talks and workshops, so maybe schedule a bit less program in favor of more programming.

For (lightning) talks: Either include in the schedule some time between talks or force all speakers to submit their slide decks in advance and to present from a common computer, so that not much time will be lost when switching devices connected to the projector.

>    5. Suggestions for improvement:
> 
> 
>    * Are there any specific topics or formats you would like to see in future events?

- AMA sessions with key members of the community.
- Talks or workshops about best practices: What should be recommended and why?

>    * Is there anything else you would like to share that would help us enhance the workshop experience?

Keep up the good work, but maybe find a way that's more sustainable than staying up all night to prepare food for the day. While the resulting dishes were delicious, that modus operandi can't be good for your health.

**Comment by infinisil** [comment]
The organization was great overall! Big kudos to @ners and @fricklerhandwerk for organizing this! Some minor things could be improved though:

  3. Registration was a bit odd for people attending on Sunday as well, since there were two separate events, and the one on Sunday being created only weeks in advance (once we got confirmation about the workshop happening).
  
      Suggestion: Create the two events or a single one spanning two events from the start. It's great to meet people even if there's no workshop.
  5. The communication channels were a bit messy since there were two Meetup channels (the comments and the event chat), but then also an unofficial Matrix one. Also most people didn't get notifications for channels.
  
     Suggestion: Create an official Matrix channel from the start and link to it from Meetup. Suggest everybody to enable notifications for the Matrix channel.

However, I did not enjoy the workshops very much:
- They were too long, they lasted about 6 and 5 hours on Saturday and Sunday respectively. It's really hard to stay engaged for this long.
- I don't think they were very fruitful:
  - Imo the biggest end result from Saturday was that some people said they might be able to commit some time or ask their companies to try Nix. I don't think a 6-month plan was achieved and I don't think it could've been achieved.
  - For Sunday, we at least had this one idea that it might be good to have multiple websites for the different user groups. But instead of e.g. concretely brainstorming on that idea, we went through various exercises only to end up with a vague diagram of various key words and questionable usefulness.
- It preventing interesting discussions from developing: During the workshop we had some occasions where some really good discussions started, but instead of being able to continue them, we had to stop to be able to finish with the workshop on time.

Instead to me, the most enjoyable parts about this event were:
- The ~1.5 hour timespan before the workshop on Saturday, where we had time to actually hack on ZHF. I was able to help a bunch of people figure out breakages and debug problems.
- Chatting for an hour with @flokli about tvix on Sunday. Even though I was slowly dying of allergies, it was really nice to learn about some interesting ideas

I would've liked just more room for everybody to chat and hack together. Yes we should probably have _some_ organization of activities, but let everybody decide more over what they want to be doing.

Concretely here's an idea:
- At the start of the event, or even beforehand, give everybody a chance to propose activities. This should include things like:
  - What is the activity, what is the outcome of it (if any)
  - Who leads this activity (if any)
  - Who should participate, calling out specific people critical to the activity (if any)
  - How long it takes (or if it's just continuous, like the ZHF hacking)
  - Whether the activity should be streamed and/or recorded.
- Plan the activities
  - Have everybody signal which activities they'd be interested in participating.
  - Plan whether, when and where the activities will be, based on available time, spaces, equipment and people.
    This is essentially a resource management problem: We have certain people, rooms, equipment and time available, how do we allocate those?
  - Announce the plan on a whiteboard and Matrix, so everybody can always know what's happening and dynamically decide what to do.
    - There should also always just be a hang-out area without any particular activity going on, for random discussions.

- Start the activities!

For me particularly this would've given me the opportunity to e.g. propose an activity to talk about module system changes with @roberth for an hour, or to discuss the [Packages Modules WG](https://github.com/nixpkgs-architecture/pkgs-modules/) with @DavHau and @edolstra. Anybody interested could've joined those conversations as well.

**Comment by infinisil** [comment]
> No major ones, but we should maybe ask speakers not to touch any buttons of the projector panel without consulting the local guy (this time: me) first. Some turned off the projector unnecessarily, which cost some time (because the projector can't be turned back on before it has cooled down or whatever) and thus (slightly) added to the schedule delays.

Yes that was me :sweat_smile:. To my defense, the documentation on these buttons is really bad!

**Comment by ners** [comment]
> It'd be good to pro-actively reach out to volunteers like me, so that they don't have to inquire when they should be where (like I had to)

I suspect this will get better now that we're connected on Matrix. Email and text messages are a bit tricky, especially with a busy schedule.

> maybe find a way that's more sustainable than staying up all night to prepare food for the day

It wasn't all night, a team of four worked for 2 hours on the night before the event, and 1 hour in the morning before. We got enough sleep. :slightly_smiling_face:

**Comment by lorenz** [comment]
Organization was great, food was great and I got to meet some great people! I do however share some of @infinisil's pain points about the workshops. They were very long (especially plenum time) and kind of got in the way of hacking and talking to people while IMO not bringing too much value.

**Comment by imincik** [comment]
@ners , @fricklerhandwerk and @das-g big thank you for organizing this event and putting so much energy in to it.

I very much enjoyed Switzerland as a country, the venue was perfect, Internet connection fantastic, Saturday's food fantastic (I missed Sunday's BBQ, so I can't say). And I very much enjoyed all people around. 
I very much appreciate attention in to details like badges printed on both sides and finally nice NixOS stickers !

1. Organization
Meetup registration was OK, except quite last minute announcement of Sunday's event. For the next time, I suggest not splitting this event to multiple ones. Communication via Matrix was good.

2. Content

Saturday

I very much liked the idea of creating ecosystem diagram, but I was expecting doing it in much more detailed level.

I also liked the idea of collecting and describing the list of major issues we have, but again, maybe we could spend little more time defining them, analyzing them and looking for common patterns.

What I didn't like was what has followed. The quick creation of teams forced to quickly produce some results and commit in to them. 

The reasons are following:
* not everybody came to this meetup to commit in to something (or is able to commit)
* even if I would be very happy to do some work, I think you need much, much more time to establish brand new team, discuss what you want to do and how and then be comfortable to commit in to some work
* and the biggest problem with that kind of forced hunt for plan and results was the fact that it was killing very interesting discussions we started to have. They could actually lead to some significant ideas if we could have enough time to finish them.

Also, working on tight schedule for such a long time was preventing people to have potentially very fruitful interactions which otherwise could happen. Especially when you have so many experts present in one room for a whole day.

3. Suggestions for improvement

For the next time, I suggest to leave much more room for free discussions and work and also offer some time and help for less experienced or new people.

Thank you very much again and I am looking forward to see you all again.

**Comment by Nebucatnetzer** [comment]
Hey everyone!

First of all thank you very much for the organisation!
I had a great time regardless of the points that I will mention below, just to make this clear right at the start.
It was really nice to meet everyone and being able to talk with other and especially more experienced Nix users.

1. Organisation

As mentioned by others it would've been better if the the Meetup appointment was for two days. I didn't realise that it was a two day event and had already plans for Sunday.
One place for communication would be less confusing, I personally like Discourse because of it is asynchronous but could work with Matrix.

2. Content and 3. Atmosphere/Networking

I didn't actually plan to participate in the workshop. @christianharke and I had the expectation that there would be more focus fixing the Hydra issues.
It would've been a nice possibility for us to get to know the ins and outs of Nixpkgs better.
While I've been using NixOS for about two years now I still wouldn't feel comfortable to contribute code to it, yet.
Same goes for having a say in the organisation, while I see certain problems I don't really know if they are the most pressing issues.
The few minutes where @infinisil helped me debugging the Emacs packages already taught me quite a bit.

What I saw of the workshop, I found the first two segments interesting.
I felt the second part was very ambitious but I only watched that from the side and maybe I'm mistaken.

The time we then had in the afternoon was nice and could've been much longer.
Which I think, speaks highly for the atmosphere.

4. Logistics

The food was very tasty!

Even though I only partially participated in the workshop it felt that the sessions were too long and the breaks too short.
Especially with such a complex coffee setup.
A nice lunch break probably wouldn't have hurt either.

As others mentioned as well more badges or a temporary PIN to the door would be nice.

For beginners it might be useful to fix one or two packages together on the beamer and/or reserve a few packages which might be better suited for beginners.
A lot of the failures that were left were libraries were it is helpful to know the ecosystem.
With the current number of attendees a short introduction round might've been possible as well.

I'm really looking forward to the next meeting!

All the best

Andreas (Nebucatnetzer)

**Comment by ners** [comment]
Dear Nixers,

Thank you for all the valuable feedback you've provided. Here are some things we want to improve for the next event:

1. Prioritise hacking:

    We will more clearly communicate that workshops are *entirely optional* to ensure that attendees can choose their preferred level of engagement.

    We will try to cut down on workshop length.

    We may also appoint dedicated individuals or teams to stay in the hacking track during the event, providing continuous assistance and guidance.

2. Streamlined communication:

    **Matrix will be the primary communication channel moving forward.**

    We intend to keep using Meetup for event planning, but we'll likely not create separate events for separate days.

5. Planning optimisation:

    We will try to provide more people with door access, or ask for the door to stay unlocked altogether.

    We will also ensure that event details are shared in a more timely manner.

We're looking forward to welcoming you back soon!

The Nix Zürich team

**Comment by imincik** [comment]
Thank you Alexei
