### ISSUE TITLE
23.11 ZHF Developer Workshop Feedback

### ISSUE THREAD

**Issue by ners** [nix-community/ZurichZHF#3]
Dear Nixers!

Thank you for participating in the hackathon and UX workshop that we ran on 2023-11-25 and 2023-11-26. We sincerely appreciate your presence and active involvement in making it a successful event. We would like to hear your feedback and insights to help us improve future events. Your input is invaluable to us!

We kindly request you to take a few minutes to provide your feedback. Here are some example questions to consider; **you don't have to answer all of them**.

1. Organisation:
  - How would you rate the overall organisation of the event?
  - Did you find the registration process smooth and hassle-free?
  - Were the communication channels (Meetup, Matrix room) effective?

2. Content:
  - Is there a topic you would like to explore in future workshops?
  - Did the workshop content align with your expectations and needs?
  - Which specific topics or areas covered during the workshop were most valuable to you?
  - Were there any topics or areas that you felt were lacking or could be improved upon?

3. Atmosphere and networking:
  - Did you find the event environment conducive to learning and networking?
  - Were there enough opportunities to interact with other attendees and exchange ideas?
  - Did you feel comfortable asking questions and participating in discussions?

4. Logistics:
  - Were the venue and facilities suitable?
  - Did you encounter any issues with seating, electrical equipment, or other logistics?
  - How would you rate the overall timing and duration of the event?

5. Suggestions for improvement:
  - Do you have any suggestions or ideas for improving future events?
  - Are there any specific topics or formats you would like to see in future events?
  - Is there anything else you would like to share that would help us enhance the experience?

@augustebaum
@chysi
@das-g
@delroth
@edolstra
@Eltonux
@fricklerhandwerk
@gefla
@imincik
@infinisil
@ivanbakel
@jeremystucki
@john-rodewald
@jsvilling
@Linschlager
@lorenz
@mfrischknecht
@MMesch
@Nebucatnetzer
@prtzl
@sdier
@tricktron
@twesterhout
@zimbatm
@zopieux

**Comment by imincik** [comment]
For me, everything was really great, registration, organization, food, agenda. Both days I stayed in a hacking room and I enjoyed it very much. I believe, tireless support provided @infinisil was invaluable for everybody and was key to success for all ZHF participants. I also very much enjoyed all chats with other people. Big thanks everyone ! Looking forward to see you next time.

**Comment by zopieux** [comment]
Definitely more productive than I'd have imagined initially. Mostly came for the hacking opportunities and talking with folks. The food and drinks were a nice plus! I only came on Saturday so I could finish some work on Sunday on my nicer desktop setup.

I'll probably join the next meetup if I'm around :-)

Thanks a lot for the flawless organization!

**Comment by MMesch** [comment]
Great workshop and organization. Therefore not much to say from my end other than that I can recommend it to anyone having the time.

**Comment by Nebucatnetzer** [comment]
It was a great weekend and I learned a lot, thank you all for your time organizing the event!

I don't want to belittle the effort of the other organizers in any way but I agree with @imincik that @infinisil deserves special praise for his endless patience with answering our endless questions :).

I'm definitely looking forward to the next event.

**Comment by infinisil** [comment]
I'm glad I was able to help so many people, I'm looking forward to next time!

Some feedback from my side:
- Using Matrix worked really well, I loved seeing everybody post links all the time!
- I think it's great that people didn't feel forced to join the workshop. It's definitely not something for everyone (me included)
- I didn't join the workshop, but from what I heard, it went over the allocated 1 hour slots. I think it's very important to always be on time, so people can set their expectations.
- At one point I noticed that the air in the hacking room was rather stuffy, we opened the window (though there was only a tiny one). I think it would be great to open the window from the start if possible.
- I'm terrible at remembering things, including faces. As an idea to help a bit with this, I'd suggest everybody to have a decent face picture on meetup.com (only if you're okay with that of course!)
- The restaurant experience on Saturday was a bit messy. In the end it worked out fine, but it might be better to plan for that more in advance so that everybody knows where they're heading in the evening.
- I definitely wasn't drinking enough though, and I also noticed that we didn't have water bottles for some time. Maybe something could be done to encourage more hydration :thinking: 
- Not sure if we can do anything about this, but I noticed at least me being a bit burned out on Sunday afternoon (might be related to having done Nix for the past 6 days :thinking:).
- On a very technical level, it would be really useful to have a Nix build server for all ZHF architectures (`{x86_64,aarch64}-{linux,darwin}`). This way we wouldn't have to rely on CI as much.
- The λ cookies and the ones on Sunday were delicious, I loved them!

**Comment by imincik** [comment]
> On a very technical level, it would be really useful to have a Nix build server for all ZHF architectures ({x86_64,aarch64}-{linux,darwin}). This way we wouldn't have to rely on CI as much.

That's a very good idea !
